spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hamlol
    username: ham
    password: 6778
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33
